export const FETCH_HOTELS = 'FETCH_HOTELS';
export const SET_HOTELS = 'SET_HOTELS';
export const CLEAR_HOTELS = 'CLEAR_HOTELS';
export const ADD_TO_FAVORITE_HOTEL = 'ADD_TO_FAVORITE_HOTEL';
export const REMOVE_FROM_FAVORITE_HOTEL = 'REMOVE_FROM_FAVORITE_HOTEL';
export const SORT_FAVORITE_HOTELS = 'SORT_FAVORITE_HOTELS';
